services:
    controller:
        image: gachaserver:latest
        container_name: gacha_server
        build:
            context: .
            dockerfile: CardGachaServer/Dockerfile
        ports:
            - "3000:8080"
        secrets:
            - jwt_private_key
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};
            - Jwt__Key=${JWT_KEY}
            - Jwt__Issuer=${JWT_ISSUER}
            - Jwt__Audience=${JWT_AUDIENCE}
        depends_on:
            database:
                condition: service_healthy
    database:
        image: postgres:latest
        container_name: database
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    db-data:

secrets:
    jwt_private_key:
        file: ./secrets/private_key.pem
