// <auto-generated />
using System;
using CardGachaServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CardGachaServer.Database.Migrations.App
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260814093403_InitApp")]
    partial class InitApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CardGachaServer.Model.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsRegular")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Rarity");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CardGachaServer.Model.ItemPoolRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PoolId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PoolId", "ItemId")
                        .IsUnique();

                    b.ToTable("ItemPoolRelations");
                });

            modelBuilder.Entity("CardGachaServer.Model.Pool", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("CardGachaServer.Model.Probability", b =>
                {
                    b.Property<int>("Rarity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Rarity"));

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Rarity");

                    b.ToTable("Probabilities");
                });

            modelBuilder.Entity("CardGachaServer.Model.Item", b =>
                {
                    b.HasOne("CardGachaServer.Model.Probability", "Probability")
                        .WithMany()
                        .HasForeignKey("Rarity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Probability");
                });

            modelBuilder.Entity("CardGachaServer.Model.ItemPoolRelation", b =>
                {
                    b.HasOne("CardGachaServer.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardGachaServer.Model.Pool", "Pool")
                        .WithMany()
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Pool");
                });
#pragma warning restore 612, 618
        }
    }
}
